from src.core.config import settings

OUTPUT_FORMAT = settings.OUTPUT_FORMAT
AUDIO_CHANNELS = settings.AUDIO_CHANNELS
TARGET_RATE = settings.TARGET_RATE
FFMPEG_BINARY_PATH = settings.FFMPEG_BINARY_PATH
PROCESS_TIMEOUT_SECONDS = settings.PROCESS_TIMEOUT_SECONDS
