from src.core.config import settings

MODEL_SIZE = settings.MODEL_SIZE
DEVICE = settings.DEVICE
COMPUTE_TYPE = settings.COMPUTE_TYPE
BEAM_SIZE = settings.STT_BEAM_SIZE
MAX_CONCURRENT_TRANSCRIPTIONS = settings.MAX_CONCURRENT_TRANSCRIPTIONS

SUPPORTED_LANGUAGES = ["ar", "en"]
